[2023-10-24T16:00:51.896+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.transform_data scheduled__2023-10-24T15:47:36.078597+00:00 [queued]>
[2023-10-24T16:00:51.965+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.transform_data scheduled__2023-10-24T15:47:36.078597+00:00 [queued]>
[2023-10-24T16:00:51.968+0000] {taskinstance.py:1359} INFO - Starting attempt 3 of 3
[2023-10-24T16:00:52.040+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): transform_data> on 2023-10-24 15:47:36.078597+00:00
[2023-10-24T16:00:52.074+0000] {standard_task_runner.py:57} INFO - Started process 1189 to run task
[2023-10-24T16:00:52.101+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'transform_data', 'scheduled__2023-10-24T15:47:36.078597+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/tugaskel8_dag.py', '--cfg-path', '/tmp/tmpn61a86f8']
[2023-10-24T16:00:52.123+0000] {standard_task_runner.py:85} INFO - Job 97: Subtask transform_data
[2023-10-24T16:01:02.540+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 97 for task transform_data ((psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8); 1189)
[2023-10-24T16:01:03.925+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-24T16:01:03.983+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
